on:
  push:
  #  branches:
  #    - main
name: Release-Go-iOS
jobs:
  build_on_windows:
    runs-on: windows-latest
    steps:
      - name: Create Release
        id: create_release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_schema: semantic
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          get-content main.go | %{$_ -replace "local-build","${{ steps.create_release.outputs.current_tag }}"}
          mkdir bin
          go build -ldflags="-s -w" -o bin/ios.exe
          echo ${{ steps.create_release.outputs.current_tag }} > release_tag
          Compress-Archive -Path .\bin\ios.exe, release_tag -CompressionLevel Optimal -DestinationPath go-ios-windows.zip
      - name: upload the windows build
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: go-ios-windows.zip
          retention-days: 1
  