on:
  push:
    branches:
      - master
name: Release-Go-iOS
jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          brew install gnu-sed
          alias sed=gsed
          gsed -i 's/version \= \"local-build\"/version = \"${{ steps.create_release.outputs.current_tag }}\"/' ios.go
          go build -ldflags="-s -w"
          zip go-ios-mac.zip go-ios
      - name: upload the macos build
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: go-ios-mac.zip
  build_on_linux_and_release:
    runs-on: ubuntu-latest
    needs: build_on_mac
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_schema: semantic
      - name: Build
        run: |
          sed -i 's/version \= \"local-build\"/version = \"${{ steps.create_release.outputs.current_tag }}\"/' ios.go
          go build -ldflags="-s -w"
          zip go-ios-linux.zip go-ios
      - name: Download mac release from previous job
        uses: actions/download-artifact@v2
        with:
          name: macos-build
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: "*.zip"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.create_release.outputs.current_tag }}
