on: pull_request

name: Unit tests
jobs:
  test_on_windows:
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: compile
        run: go build
      - name: install netcat
        run: choco install netcat
      - name: forward ngrok
        run: nc -L 127.0.0.1:22 -p 8080 -vvv
  test_on_linux:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: compile
        run: go build
      - name: install socat
        run: sudo apt install socat
      - name: ngrok
        run: |
          sudo socat UNIX-LISTEN:/var/run/usbmuxd,fork,user=mysql,group=mysql,mode=777 TCP-CONNECT:2.tcp.ngrok.io:18860&
      - name: run go test
        run: go run main.go list

