on: pull_request
# ngrok tcp 9999
# socat TCP-LISTEN:9999,reuseaddr,fork UNIX-CONNECT:/var/run/usbmuxd
name: Unit tests
jobs:
  test_on_windows:
    runs-on: windows-latest
    steps:
      - name: forward ngrok
          #run: nc -L 4.tcp.ngrok.io:16921 -p 8080 -vvv #local port -p will connect to the -L target
        run: netsh interface portproxy add v4tov4 listenaddress=127.0.0.1 listenport=27015 connectaddress=4.tcp.ngrok.io connectport=16921
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: compile
        run: go build
      - name: test list
        run: go run main.go list
      - name: try install
        run: go run main.go install --path .\testdata\wda-signed-test.ipa --udid=8a4b8ae031a0565729e92b836e82bccc4540f8fd

  test_on_linux:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: compile
        run: go build
      - name: install socat
        run: sudo apt install socat
      - name: ngrok
        run: |
          sudo socat UNIX-LISTEN:/var/run/usbmuxd,fork,user=mysql,group=mysql,mode=777 TCP-CONNECT:2.tcp.ngrok.io:18860&
      - name: run go test
        run: go run main.go list

